# Generated by Django 2.0.2 on 2018-02-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0002_auto_20180211_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Free', 'Free Text Question'), ('Multi', 'Multiple Choice Question')], max_length=100),
        ),
    ]
