# Generated by Django 2.0.2 on 2018-02-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0004_auto_20180211_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Free', 'Free Text Question'), ('Multi', 'Multiple Choice Question')], max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleType',
            field=models.CharField(choices=[('vendor', 'vendor'), ('owner', 'owner'), ('guest', 'guest')], max_length=100),
        ),
    ]
